// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['text!templates/deputat.html', 'views/experience_bar'], function(template, ExperienceBarView) {
    var DeputatView, _ref;
    return DeputatView = (function(_super) {
      __extends(DeputatView, _super);

      function DeputatView() {
        _ref = DeputatView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      DeputatView.prototype.template = _.template(template);

      DeputatView.prototype.el = "div#deputat-content";

      DeputatView.prototype.views = {};

      DeputatView.prototype.initialize = function() {
        this.render();
        this.views.expBar = new ExperienceBarView();
        return this.views.expBar.render().setExperience(10).addExp(10);
      };

      DeputatView.prototype.render = function() {
        return this.$el.html(this.template());
      };

      return DeputatView;

    })(Backbone.View);
  });

}).call(this);
