// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['text!templates/experience_bar.html'], function(template) {
    var ExperienceBarView, _ref;
    return ExperienceBarView = (function(_super) {
      __extends(ExperienceBarView, _super);

      function ExperienceBarView() {
        _ref = ExperienceBarView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      ExperienceBarView.prototype.el = "div#experience-bar";

      ExperienceBarView.prototype.template = _.template(template);

      ExperienceBarView.prototype.events = {};

      ExperienceBarView.prototype.render = function() {
        this.$el.html(this.template());
        return this;
      };

      ExperienceBarView.prototype.setExperience = function(experience) {
        this.$el.find("div.progress-bar").css({
          width: experience + "%"
        });
        return this;
      };

      ExperienceBarView.prototype.addExp = function(experience) {
        return console.log(this.$el.find(".progress-bar").outerWidth());
      };

      ExperienceBarView.prototype.getColWidth = function() {
        return this.$el.css("width");
      };

      return ExperienceBarView;

    })(Backbone.View);
  });

}).call(this);
