// Generated by CoffeeScript 1.6.3
(function() {
  define(['views/experience_bar', 'views/deputat'], function(ExperienceBarView, DeputatView) {
    var Deputat;
    return Deputat = (function() {
      Deputat.prototype.views = {};

      function Deputat() {
        this.views.deputat = new DeputatView();
      }

      return Deputat;

    })();
  });

}).call(this);
