// Generated by CoffeeScript 1.6.3
(function() {
  requirejs.config({
    baseUrl: "js",
    paths: {
      text: 'lib/text'
    },
    shim: {
      'lib/underscore-min': {
        exports: '_'
      },
      'lib/backbone-min': {
        deps: ['lib/underscore-min'],
        exports: 'Backbone'
      },
      'deputat': {
        deps: ['lib/underscore-min', 'lib/backbone-min']
      }
    }
  });

  require(['deputat'], function(Deputat) {
    return window.Deputat = new Deputat();
  });

}).call(this);
